apiVersion: v1
kind: Pod
metadata:
  name: chrome-setup
spec:
  restartPolicy: Never
  volumes:
    - name: shared-tools
      emptyDir: {}

  initContainers:
    - name: install-chrome-and-chromedriver
      image: debian:bullseye-slim
      command:
        - sh
        - -c
        - |
          apt-get update && apt-get install -y wget unzip curl ca-certificates && \
          wget -q -O /tmp/chrome.zip https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.94/linux64/chrome-linux64.zip && \
          wget -q -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.94/linux64/chromedriver-linux64.zip && \
          unzip /tmp/chrome.zip -d /opt/chrome && \
          unzip /tmp/chromedriver.zip -d /opt/chromedriver && \
          mv /opt/chrome/chrome-linux64/chrome /tools/google-chrome && \
          mv /opt/chromedriver/chromedriver-linux64/chromedriver /tools/chromedriver && \
          chmod +x /tools/google-chrome /tools/chromedriver
      volumeMounts:
        - name: shared-tools
          mountPath: /tools

  containers:
    - name: dummy
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
      volumeMounts:
        - name: shared-tools
          mountPath: /tools
